// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYZiHIOejMs73o6EYd8C7d-6UaGJIZzw',
    appId: '1:1002616448817:web:617ad52e91b5537db0b210',
    messagingSenderId: '1002616448817',
    projectId: 'astrology-da455',
    authDomain: 'astrology-da455.firebaseapp.com',
    storageBucket: 'astrology-da455.firebasestorage.app',
    measurementId: 'G-MDEKYMBZZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWRLhmTTC0o5urFsaW1FCjLXRgrGQ7p8',
    appId: '1:1002616448817:android:0c771fcdd193f622b0b210',
    messagingSenderId: '1002616448817',
    projectId: 'astrology-da455',
    storageBucket: 'astrology-da455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwmZk0ocglQnM84cJmwKjXNcb1s5eVPg',
    appId: '1:1002616448817:ios:5ac85a8683d816f5b0b210',
    messagingSenderId: '1002616448817',
    projectId: 'astrology-da455',
    storageBucket: 'astrology-da455.firebasestorage.app',
    iosBundleId: 'com.example.astrologyUser',
  );
}
